additional:
  - "terraform-*"

files:
  - "!.gitignore"
  - "!.github/template-sync.yml"
  - "!.pre-commit-config.yaml"
  - "!Makefile"
  - "!.github/dependabot.yml"
  - "!.github/workflows/sync.yaml"
  - "!*terraform/*"
